- dist/module/actor/entity.js
- dist/module/combat.js
- dist/module/dice.js
- dist/ose.js
here are the fixes for the combat tracker, as well as implementing the item Id information needed for the Automated Animations module dev to add support for OSE
> combat tracker fix, added flags to weapon rolls

- dist/module/combat.js
- src/module/combat.js
> Fix to automatically set flag in combat tracker (Issue #6)

- system.json
Add support for https://github.com/League-of-Foundry-Developers/bug-reporter as per #49
> Add FVTT Bug Reporter module support

- src/templates/chat/license.html
> Templating on Settings tab updated to link to GitHub Issues

- src/module/actor/entity.js
Fixes #24 
The initiative bonus calculation was using the wrong variable
> fix(combat): initiative dex modifier corrected

- dist/module/dice.js
- src/module/dice.js
Fixes #67 ability dice rolls with type equals not working
> Fix #67 dice equals

- NOTICE
- gulpfile.js
- package-lock.json
- package.json
- rollup.config.js
- gulp is now on version 4, which allows us to introduce parallel task running. Styles compilation, code rollup, and file static file copying all happen in parallel
- Rollup and source mapping has been introduced
- All dev dependency vulnerabilities are now resolved
> Dev dependency updates for improved developer experience

- .github/workflows/release.yml
Improved the GitHub Action workflow to allow it to cache dependencies, which will make it a lot faster
> build: caching npm dependencies

- package-lock.json
- package.json
- system.json
Freohr and I found a bug in a dependency. It appears to be caused by inconsistent behavior with the preinstall script for forcing resolutions on dependencies. Reverting back to the old behavior
> fix: reverting some dependency changes

- src/module/fvttModuleAPIs.js
- src/ose.js
- template.json
Implements the Item Piles API to manually set the necessary values needed (specifically actorType and itemQuantityAttribute)
> feat: native support for Item Piles

- src/module/fvttModuleAPIs.js
- src/ose.js
This fix contributed by @RabidOwlbear
> fix: itempiles API incorrectly referenced

- src/module/treasure.js
Quick fix for the "Treasure Table" problems encountered in #80
> Fix error on Treasure Table "update" and "add" + visual fixes

- src/templates/actors/partials/monster-attributes-tab.html
> fix: removed "other items" from attributes tab

- src/module/dialog/party-sheet.js
This seems to fix the issue of actors not being able to be added to the party sheet.
> actor drop fix

- src/templates/actors/partials/character-inventory-tab.html
> fix: monsters no longer have equip toggles

- src/module/actor/actor-sheet.js
- src/module/actor/character-sheet.js
- src/module/actor/monster-sheet.js
- src/templates/actors/partials/character-inventory-tab.html
> fix: item quantity editable in sheet again

- src/module/actor/actor-sheet.js
> fix: containers can't contain each other anymore

- src/module/actor/actor-sheet.js
- src/module/actor/entity.js
> fix: treat cmd + click the same as ctrl + click

- src/module/settings.js
bug: system settings are not being correctly saved.
fix: removed the onChange key from the system settings objects.
> fix: settings not persisting on save changes

- src/module/actor/actor-sheet.js
> fix: contained items drop into new sheets unhidden

- src/module/actor/entity.js
> fix: movement now degrades above weight limit

- src/templates/chat/roll-treasure.html
(Edit: removed because I reworded the title)
> Fix the display of the resulting chat card when rolling treasure tables recursively

- src/module/helpers.js
- src/templates/actors/partials/character-header.html
> fix: remove gt handlebarHelper in favor of gte

- src/templates/actors/character-sheet.html
- src/templates/actors/monster-sheet.html
> fix: missing sheet tabs in v10

- src/module/item/entity.js
- src/templates/actors/partials/actor-item-summary.html
- src/templates/items/item-sheet.html
> fix: item summaries and show item to chat

- src/module/actor/actor-sheet.js
- src/module/actor/character-sheet.js
- src/module/party/party-sheet.js
- src/module/party/party.js
- src/ose.js
> Revert "Party sheet"

- src/module/actor/actor-sheet.js
- src/module/actor/character-sheet.js
- src/module/party/party-sheet.js
- src/module/party/party.js
fixes the container item duplication bug, and fixes the broken party sheet. Have not tested on a v9 client.
> party sheet/container fix

- src/module/item/item-sheet.js
- src/templates/items/ability-sheet.html
- src/templates/items/armor-sheet.html
- src/templates/items/container-sheet.html
- src/templates/items/item-sheet.html
- src/templates/items/spell-sheet.html
- src/templates/items/weapon-sheet.html
fixes version compatibility for item sheets
> item templates temp fix

- src/e2e/actor/character.e2e.test.js
- src/e2e/index.js
- src/e2e/testUtils.js
- src/module/actor/entity.js
- src/ose.js
This changeset adds E2E tests using Quench, as suggested in #250.
Note: this PR is currently a WIP, as I'd like to get feedback on what I'm doing (what's valuable to test, are we testing the right way, etc).
> feature: E2E Tests for the Character sheet

- src/module/fvttModuleAPIs.js
> Updates to Item Piles' integration

- src/module/actor/entity.js
> fix: hit die roll adds con modifier for each level

- src/module/party/party-sheet.js
- src/templates/apps/party-sheet.html
This changeset allows the user to drag a folder of characters into the party sheet. It also allows the user to drag an actor from the party sheet to the scene.
> fix: Party sheet ergonomic fixes

- src/module/actor/actor-sheet.js
- src/module/actor/data-model-classes/data-model-character-spells.ts
- src/module/actor/data-model-monster.js
- src/module/actor/entity.js
- src/module/actor/monster-sheet.js
- src/module/dice.js
- src/ose.js
- src/templates/actors/partials/character-inventory-tab.html
This changeset adds a data model for the Monster actor type. it also scrubs some now-obsolete code from sheets and entities.
> feat: Add a data model for Monster actors

- src/module/actor/actor-sheet.js
- src/module/actor/data-model-monster.js
- src/module/actor/monster-sheet.js
This changeset fixes some stuff we didn't catch when monster data models went in the first time. Oops!
> fix: Monster Data Model bugfixes

- src/lang/de.json
- src/lang/en.json
- src/lang/es.json
- src/lang/fr.json
- src/lang/it.json
- src/lang/pt-BR.json
- src/module/actor/actor-sheet.js
- src/templates/items/delete-container.html
Added a confirmation dialog that proceeds with deleting a container if user selects "Ok".
This only shows when deleting a container that is containing items.
> [enhancement] Container delete confirmation

- .eslintrc
- .prettierrc
- package-lock.json
- package.json
- src/module/actor/actor-sheet.js
- src/module/actor/character-sheet.js
- src/module/actor/entity.js
- src/module/actor/monster-sheet.js
- src/module/combat.js
- src/module/dice.js
- src/module/helpers.ts
- src/module/item/entity.js
- src/module/item/item-sheet.js
- src/module/renderList.js
- src/ose.js
- src/ose.scss.js
This changeset is meant to show what kinds of changes we can expect to see as we work through linting:
* Changing `==` to `===` and `!=` to `!==`
* Adding some JSDoc frontmatter for file summaries
* Sorting imports
* Changing `let` to `const` (when reasonable)
* Changing from loops to array iteration (where reasonable)
* Avoiding mutation of arguments (where possible)
> chore: A taste of linting (ose.js, ose.scss.js, == to ===)

- src/module/dialog/__tests__/sheet-entity-tweaks.test.ts
Small fix that caused the system not to build on 1.8.x.
> fix: entity-tweaks-tests

- CONTRIBUTING.md
- foundryconfig.json.example
- tools/symlink.js
resolves #312 
While experimenting with the latest v11 prototype, I figured I'd fix this so I don't have to edit the config more than necessary.
> Symlinker now supports array of dataPaths

- AUTHORS
- system.json
Basic contributor information and AUTHORS file up to date with info submitted in #59
> chore: update authors file and contributor info

- src/templates/chat/item-card.html
> fix: removed disabled prop from button tag

- src/module/item/item-sheet.js
> feat: make item window resizable

- src/module/actor/entity.js
- src/module/item/entity.js
Resolves #32 
Adds data migration for actors and items to set default image if missing.
> chore: data migration to default img

- src/module/dialog/character-creation.js
- src/module/dialog/entity-tweaks.js
- src/templates/actors/dialogs/tweaks-dialog.html
> fix: deprecated data object calls

- .github/ISSUE_TEMPLATE/bug.yml
V11 is here, I think we have 3-4 bugs logged for it. It's past time to update the bug template as well
Happy to hear other incidental feedback on the bug template in your review as well!
> chore: update bug template for V11

- src/templates/actors/partials/character-header.html
> fix: alt tag for Shopping Cart corrected

- src/templates/chat/roll-attack.html
Fixes #421, which I missed while fixing #370 in 1.7.7
> fix: remove disabled prop from tag, again

- src/module/actor/entity.js
> fix: str and dex modifier now added to damage roll

- docs/index.html
Please leave feedback about things that may have been missed (wrong, outdated, poor wording/confusing grammar). I think we can make style improvements next time, as well as update screenshots next time
> docs: update text to include the sheet redesign

- src/lang/en.json
- src/module/helpers-macros.js
- src/module/helpers-treasure.js
- src/ose.js
Attempts to address, #355 
Allows dropping RollTables onto Hotbar, resulting in Macro creation to Roll on them.
If this implementation is acceptable (hi-jacking existing if statement, heavily oriented around Items) - i'll go ahead and modify/write tests.
If this wants re-writing, to be more generic, let me know and i'll do that first.
> fix(macros): #355 Accept RollTable drops onto Macro hotbar

- src/module/combat/combatant.ts
This fixes the initiative mod not working when rolling for individual initiative
> Pass actor RollData to initiative roll

- src/module/helpers-party.js
- src/scss/apps.scss
Puts the button on the search line before the search icon.  Adjust as necessary.
> Party Sheet button fix
