vttred/ose

- src/module/actor/entity.js
Taken from the original PR [here](https://gitlab.com/mesfoliesludiques/foundryvtt-ose/-/merge_requests/14)
This PR should cover bugs reported in issue #4:
For Basic encumbrance:
* Armor correctly reduces your movement speed
* Max encumbrance is based on the "Tweaks" value (1600 by default as per the rules), not based on the "Significant Treasure" option value
* Speed is correctly negated when at or above the max encumbrance
* the "Significant Treasure" value is shown as an encumbrance step (smalls arrows, like for Detailed Encumbrance)
For Detailed encumbrance:
* Adventuring Equipment is correctly detected: the "package" encumbrance of 80cn is 0 with no equipment, and 80 with any kind of gear (that is not: Armor, Weapon, Container or Treasure).
For all
* Speed reduction weight brackets …
> Encumbrance fixes

- dist/module/actor/character-sheet.js
- src/module/actor/character-sheet.js
Since the implementation of the tooltip is so far from finished, I created a new enhancement request issue #21 for this feature.
The event listener is commented out with a note leading back to issue #20. The event listener itself isn't implemented incorrectly, but it calls a private function that is implemented incorrectly.
> fix: removed event listener causing #20

- src/lang/en.json
- src/module/combat.js
* hovering over the wand combat flag icon now shows the tooltip "Spell Declared"
* hovering over the running combat flag icon now shows the tooltip "Retreating from Melee Declared"
> fix: added missing tooltips to combat flags

- src/module/dialog/party-sheet.js
The party display filters out non-"characters", but using the "party" could be useful outside of the party sheet, so non-characters (only monsters for now) actors cannot get in the party.
It's a non-issue, but it was bothering me when I woke up this morning :cold_sweat:.
> Prevent adding non-"character" actors to party

- dist/ose.css
- src/scss/actor-base.scss
Fixes #25 
This is purely a "naive" patch: I found the correct behavior in V9 to be suitable, so I copied a set of attributes to the correct CSS selector and confirmed that it worked in 0.8.9. I was unable to account for any differences in behavior, but this points to a necessary audit/refactor of the CSS (possibly when we start evaluating a character sheet overhaul).
> fix(styles): nowrap tabs on character sheet

- dist/lang/en.json
- dist/module/combat.js
- dist/module/item/entity.js
- dist/templates/chat/roll-individual-initiative.html
Made changes to the individualInitiative function in the combat.js module:
- reformatted the chat message data to be more consistent with the preferred implementation for dice so nice.
- added a check to disable dice animation if the number of combatants exceeds 15.
> fix: individual initiative dice spam

- AUTHORS
- CONTRIBUTORS
Thanks to all you lovely contributors! Since this is the first PR with contributors names being added, I should explain both files quickly
CONTRIBUTORS: these are individuals' names, no matter who owns the copyright to a given contribution we're interested in officially recognizing the names of contributors!
AUTHORS: this is a list of copyright owners of code or translations in the system. Remember that even though we've released our contributions under an open source license, we all retain copyright to our contributions. If, for example, an employee of Necrotic Gnome were to make a contribution to the code for their job, Necrotic Gnome owns the copyright, not the employee.
> Added 5 contributors' names to AUTHORS and CONTRIBUTORS

- src/module/actor/monster-sheet.js
> fix: weapons now showing in monster inventory

- README.md
- docs/index.html
Got an email requesting support yesterday, which shows a need to clarify the proper channels for support requests.
> docs: add links to places for user support

- src/module/dialog/party-sheet.js
Just basic stuff, I didn't check how folders contained each others when refactoring the party sheet, so there it is.
As a bonus, I added checks to avoid any computation when trying to drop non-actor folders and items on the party-sheet.
> Lookup folder recursively to add characters to party

- src/module/actor/entity.js
- src/module/config.js
Updated the config.js file to add the arrays needed by [Let me roll that for you!](https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy).
Notes:
* I'll create the pull request on their side when this is integrated, I don't want to have users try that module and have it not work.
* If anyone wants to test, you can checkout my forked branch [here](https://github.com/freohr/fvtt-module-lmrtfy/tree/feature/add-ose-support) 
* I don't know how to integrate roll of abilities (such as Thief skills), as they are handled as an collection of Items (with the roll logic actually in the Item, not the Actor it's attached to) in this system, and LMRTFY looks for methods on the actors to enable asking for rolls.
> Update config to prepare support for "Let me roll that for you!"

- src/module/actor/actor-sheet.js
- src/module/actor/character-sheet.js
- src/module/actor/monster-sheet.js
- src/module/item/entity.js
- src/module/item/item-sheet.js
- src/module/preloadTemplates.js
- src/module/renderList.js
- src/scss/actor-base.scss
- src/scss/character.scss
- src/scss/monster.scss
- src/templates/actors/monster-sheet.html
- src/templates/actors/partials/actor-item-summary.html
- src/templates/actors/partials/character-abilities-tab.html
- src/templates/actors/partials/character-inventory-tab.html
- src/templates/actors/partials/character-notes-tab.html
- src/templates/actors/partials/character-spells-tab.html
- src/templates/actors/partials/monster-attributes-tab.html
- src/templates/items/weapon-sheet.html
**New Features**
* Content of containers is displayed as a category (like Weapons, Armor or Treasure) linked to the container item display, to enable ease of use and readability of their content
* Monsters' attack pattern groups are now separated by a small margin for ease of readability (a happy little accident I found neat while refactoring the internal structure of this display)
**Internal refactor**
Oh god so much stuff (<- this is not mandatory to include in the release notes)
* Item summary display (for weapons, armors, items, containers, treasure, monster abilities, spells, etc.) is no longer generated with JS, but is contained in an Handlebars template
* Item tags are now accessible in two data fields: `data.autoTags` and `data.manualTags`, which respectively represents tags …
> Display containers as categories for ease of use + Inventory HTML/JS refactor

- src/templates/actors/partials/character-abilities-tab.html
I removed a class on the HTML of the Item list elements, but the default drag&drop Foundry implementation depends on it, so I added it back
> Re-add a HTML class required for abilities drag&drop from inventory

- src/templates/chat/roll-attack.html
Now successfully passing actor and item ids with the weapon attack roll chat card template
> fix: missing underscore broke Maestro

- src/module/actor/actor-sheet.js
Fixed incorrect property name that was preventing the tweaks menu from being accessible on a user owned actor sheet.
> Fix: tweaks icon not showing for non gm users

- template.json
My fix to #30 isn't working in 1.4.3 because another upstream change (possibly #134 ?) had not made it to my local machine somehow, or perhaps I was testing with items that were created before that patch had been merged into main.
This is proven to rectify the issue on newly created items. We may need a proper world migration to ensure users don't have issues with items created in the interim of this patch and #134.
> fix: added manualTags and autoTags to system template

- src/module/helpers.js
- src/templates/actors/partials/actor-item-summary.html
Added a new handlebars helper that returns enriched HTML.
Changed template partial actor-item-summary to use the new helper to enrich item summary display text.
This fixes actor item summaries failure to display inline rolls correctly.
> actor sheet inline roll render fix

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
- README.md
Introducing issue templates makes it easier for less experienced users to submit useful issues for their first time, hopefully increasing the number of issues we receive.
Providing the links to docs and the Discord server in the issues tab hopefully improves the number of people providing feedback on docs and joining the Discord server to ask relevant questions.
> Issue templates

- src/module/actor/monster-sheet.js
- template.json
This PR addresses https://github.com/vttred/ose/issues/35
* For monsters, sort Abilities & Equipment by attack pattern, then weapons before abilities, then alphabetical.  
*Sort inventory and spells alphabetically within groups.
* Set ability default attack pattern to transparent (was white), 
* include transparent in attack pattern cycling
This is my first PR here and I am not experienced with javascript, so any suggestions for improvements are welcome!
> Issue #35: monster abilities and equipment sort order rework

- .github/workflows/release.yml
- system.json
system.json will now show
```
name: "ose-dev",
id: "ose-dev",
title: "Old-School Essentials Development Build",
```
Please update your symlinks to match the new name
> chore: migrate to "ose-dev" package name

- src/lang/en.json
- src/lang/fr.json
- src/module/party/party.js
- src/scss/apps.scss
- src/templates/apps/party-sheet.html
- src/templates/apps/party-xp.html
I noticed that the question "How do I add characters to the party?" is asked a bit too much in the Discord, so I added a placeholder text that should have been there when I reworked this window >.>
> Add a placeholder text to the Party overview when empty

- src/templates/items/spell-sheet.html
This changeset adds a missing "isV10" conditional and a missing curly at the end of an editor block to the spell sheet template.
> fix: Get spell sheet template to render

- src/templates/actors/partials/monster-attributes-tab.html
This changeset adds the `item` class to attacks/abilities on the monster sheet's attributes tab.
Note: this could also be resolved by changing the selector at `actor-sheet.js:88` from `.item-entry.item` to `.item-entry`. I went with the most localized change.
Fixes #242
> fix: Monster abilities and weapons can expand to display their descriptions

- src/module/actor/monster-sheet.js
This changeset allows users to delete a monster's treasure rolltable by right clicking on it. It also allows monster treasure tables to successfully get added to the monster.
**Note**: I'd appreciate if someone familiar with maintaining v9 compatibility could have a look at this; I've been so buried in v10 work these days that I've lost track of what works in v9 vs. v10 :)
Fixes #226
Fixes #227
> fix: Read and delete treasure tables on Monster sheets

- src/module/actor/actor-sheet.js
- src/module/dialog/entity-tweaks.js
- src/templates/actors/dialogs/tweaks-dialog.html
- src/templates/actors/partials/character-spells-tab.html
This changeset does a bunch of little tweaks, uncovered while I was working on some data model changes:
* Switched from `data` to `system` on the "is this a spellcaster" checkbox in the actor tweaks
* We don't rerender the actor sheet until after the tweak modal has finished updating the actor
* Max spell slots should be visible and editable again
* Clicking a spell slot field won't toggle the spell level accordion anymore
> fix: Little UX fixes around spellcasting

- src/module/actor/character-sheet.js
This changeset fixes the disappearance of attack and initiative modifiers. It also gives us a lesson for using getters on the data models: we need to re-add them to the sheet context, since the way Foundry clones `actor.system` doesn't clone getters.
Fixes #271
> fix: Attack/Initiative modifiers are visible on the sheet.

- src/module/treasure.js
Fixes #268 
This was a case of the default enriched text behavior switching to async, and we missed this particular usage of it
> fix: async restores treasure result text

- src/module/combat.js
fixes #200 
To test, change system combat settings to "Individual Initiative" and "Reset Each Round"
Roll initiative for some characters, and then start the combat. It should allow each character's individually-rolled initiative to stay
Please review the behavior to see if you have any ideas to improve the overall experience. I think it's still not perfect
> fix: don't reroll on round 1 if already rolled

- .github/workflows/release.yml
Unfortunately a fix I had implemented in October for build caching was seemingly never tested (it only ever rears its head in GitHub Actions).
The original fix `--ignore-scripts` still doesn't prevent husky from throwing an error when caching is enabled. We don't even use husky, it's a dependency for the type definitions.
We don't particularly need to cache our dependencies, it's just a best practice. I'd like to return to this when we're not late for a planned release
> fix(temporary): removed caching from the build ci

- src/module/actor/character-sheet.js
- src/module/party/party-sheet.js
- src/module/party/party.js
This changeset fixes two regressions surfaced after the release of 1.7.1:
1. Sheets for Actors of type Character did not render the correct AC scheme
2. Actors of type Character could not be added to the party overview.
Fixes #285
Fixes #288
> fix: AC/AAC display fix + party overview fix

- src/module/actor/actor-sheet.js
- src/module/dialog/character-creation.js
- src/module/item/data-model-item.js
- src/module/item/item-sheet.js
- src/templates/items/armor-sheet.html
- src/templates/items/item-sheet.html
This changeset fixes some additional bugs found by users, namely:
* The character generator once again generates stats
* Treasure items created from the character sheet once again go into the correct heading
* Items of `item` type should once again display their descriptions
Note: I'm not 100% sure how to test the item description fix, but I'm happy to take suggestions!
> fix: Additional v1.7.x fixes

- src/e2e/actor/character.e2e.test.js
- src/lang/de.json
- src/lang/en.json
- src/lang/es.json
- src/lang/fr.json
- src/lang/it.json
- src/lang/pt-BR.json
- src/module/actor/actor-sheet.js
- src/module/actor/entity.js
- src/module/behaviourHelpers.js
- src/module/settings.ts
resolves vttred/ose#124
Fixed the Mac-issues with Meta key for rolling, and added an option to reverse the behavior of clicking on a roll with ctrl/meta held down.
> [enhancement] Added option to revert Ctrl/Meta behavior

- src/module/dialog/character-gp-cost.js
- a const wasn't declared properly
- added a missing return when gp item isn't found, otherwise a "not found" console error gets produced
Fixes #282
> fix: shopping cart now deducts gold

- src/e2e/index.ts
- src/module/__tests__/macro.test.js
- src/module/__tests__/macros.test.js
- src/module/macros.js
resolves #311 
This fixes an issue that was reported on Discord, where the user was unable to drag existing macros to the hotbar.
I've added tests for both creating macros, and dragging an existing macro to the hotbar.
This also includes the fixes that was merged into 1.8.x in #314
> fix: Macro creation

- src/module/actor/data-model-classes/__tests__/data-model-character-encumbrance.test.ts
- src/module/actor/data-model-classes/__tests__/data-model-character-move.test.ts
- src/module/actor/data-model-classes/data-model-character-encumbrance-basic.ts
- src/module/actor/data-model-classes/data-model-character-encumbrance.ts
- src/module/actor/data-model-classes/data-model-character-move.ts
Fixes #315.
- Quarter encumbrance is now 75% base movement
- Instead of eighth encumbrance at 75% base movement, it's three-eighths encumbrance at 50% base movement
- Weight equal to each encumbrance step `[400, 600, 800, 1600]` is now correctly evaluated to `[100, 75, 50, 25]` % base movement. Weight *above* each step will step up the encumbrance!
- Additional tests added
Since the incorrect `>=` used for each encumbrance step is technically a regression, I hope you can appreciate the utility in the additional tests. These should make sure we don't make that mistake again.
> fix: encumbrance data models now reflect RAW

- src/module/dice.js
Fixes #340 and #341 
These were accessing the wrong properties of the roll object and not using strong comparison, which is at least part of why it took so long to find a problem here. Thanks to @bakbakbakbakbak's tests for discovering this
> fix: natural 1s/20s now auto fail/succeed

- src/lang/en.json
- src/module/helpers-macros.js
Macros were not permitted to be dragged to the hotbar as it was restricted to creating item macros. This fixes that behaviour.
Also adds a notification (with localization) that properly warns that the user tries to create a macro from a non-item if that is the case.
> fix(macro): Allow macro to be dragged to hotbar for 1.8.x

- src/module/party/party-sheet.js
Fixes an issue that was discovered during testing, that if a folder containing a folder that contains an actor. Dragging the head parent folder into the party sheet doesn't add the actor to the party. This should fix all levels of recursion.
> fix(party): Fix recursive folder adding for 1.8.x

- src/module/item/entity.js
During testing it was found that `spendSpell` needs to be asynchronous as it involves updating the actors, and rendering chat cards.
> fix(item): Make spendSpell async for 1.8.x

- src/module/__tests__/helpers-dice.test.ts
- src/module/helpers-dice.js
resolves #341, resolves #340, resolves #333
- Reworked tests for dice
- Moved `createMockData` and `createMockAttackData` into tests as they were only used there
- Updated  `createMockRoll` to properly mock a roll as needed by tests
- Rewrote the tests for `attackIsSuccess` to better explain functionality
- Rewrote `digestAttackResult` tests
- Updated `createMockRoll` calls
- #340 : Added tests for these cases
- Reformulated `createMockRoll` calls to calculate values instead of using hard-coded values.
- Calculations include calculating attack bonus from thac0 score.
- Rewrote `sendAttackRoll` tests
- Removed majority of tests that were just checking the chat messages for content
- Updated the mocking data to more accurately represent actual data from weapon rolling
- Dice helper
- Fixed …
> fix(dice): Dice rolling fixes for 1.8.x

- src/module/dialog/entity-tweaks.js
Putting these two in the same as it is just for convenience for testing purposes.
> fix(dialog): Added class for Entity Tweaks windows for 1.8.x

- src/module/helpers-treasure.js
This fixes the deprecation messages for `drawTreasure` using a synchronous call for evaluation of a roll.
> fix(treasure): Make drawTreasure async for 1.8.x

- src/lang/en.json
- src/module/chat.ts
- src/module/config.ts
- src/module/dice.js
- src/module/settings.ts
- src/templates/chat/roll-attack.html
Add the possibility to inflict damage from an attack to the original target of the attack. The original target is determined at the time of the attack, so even if the atytacking player changed target the damage will go to the right actor. 
Protected by `applyDamageOption` (preexisting) feature flag
fixes #287
> Apply damage to original attack target

- src/scss/actor-base.scss
This changeset clips really long item name text in actor inventories. You can hover over the item's name to see the full name.
> fix: Clip long item names off with ellipses.

- src/module/actor/__tests__/sheet-actor/sheet-actor-e2e-dragndrop.test.ts
- src/module/actor/actor-sheet.js
Resolves #357 
This is built upon fixes of item drag'n'drop that I've written for #356. I'll keep this in draft until #356 is merged into `1.8.x` as well as the fixes I've yet to create a PR for.
This introduces a simple check that if the item is being dragged onto itself, it does nothing in terms of rearranging the inventory.
> fix(item): Dragging a container onto itself pops it from inventory sheet

- src/module/actor/__tests__/data-model-character.test.ts
- src/module/actor/__tests__/data-model-monster.test.ts
- src/module/item/entity.js
Previously the tests for isNew() assumed that isNew() was written to check the actor's ability scores, and return true if they were all 0. But isNew() was actually written to check the actor's saves, because this is the best indicator for a "new" Character *and* Monster
```js
get isNew() {
return !Object.values(this.saves).reduce(
(prev, curr) => prev + (parseInt(curr?.value, 10) || 0),
0
);
}
```
I've replaced the tests for Data Model : Monster to check saves, not scores. Data Model : Character now has both, because the saves are autogenerated from the scores, and I think it's useful to check that that's still happening properly.
> fix: isNew() tests now check against saves

- src/module/config.ts
- src/module/settings.ts
This is how I prefer to define types where there is a single, constant, value: derive the type from the value. It's all based on the `as const` trick.
this removes duplicated structure, so it's easier to change the code while still allows consumers of the configuration object to be type safe.
This nullifies the `@todo How do I set this type?` comments :)
> [Suggestion] a different approach for CONFIG.OSE type definitions

- src/module/helpers-dice.js
original target was not passed correctly to chat template
> fix: apply damage to original target was broken

- src/module/combat.js
Please read #200. 
I unfortunately don't remember how I arrived at the fix in #280 that resulted in bug #338. I think it was quite difficult to find somewhere else to interrupt the unwanted behavior.
The fix here is once again crude, but it's tough because "Start Combat" and "Next Round" are semantically different operations, and we're kind of cornered into using the same initiative function for each.
I think it's worth considering a future refactor such that changes to one combat roll option no longer impact the other two combat round roll options.
> fix: individual init reroll each round now works

- src/module/actor/actor-sheet.js
This is my "elegant" one line fix for #310 
The bug is caused by itemIds that never got removed from container data when the item itself was deleted
There's an argument for creating a migration that removes phantom itemIds from containers rather than using this method. I think we could make an enhancement request for that and remove this?
> fix: containers with phantom items can now delete

- src/module/actor/data-model-monster.js
Fixes #378 (and possibly #331, I'm not sure yet if there's additional compatibility changes required)
> fix: made monster movement derived values available

- src/scss/apps.scss
- src/templates/chat/license.html
- system.json
- I'm now mildly confident that V11 will not blow up in our faces. I'd like to set our maximum compatible version to 11 a bit earlier than last time, because I think that's best for devs and it's going to be fine for users. There will be a warning that they can't migrate their worlds back to V10
- The core library for Simplified Chinese has a different than expected language tag. This corrects the system.json lang key to the correct value
- Package description and sidebar text updated to use some borrowed OSE marketing copy. Trademark has been permitted for use under contract but I'm only just now doing some housekeeping because someone brought it up on Discord recently
> chore: system.json changes, other superficial changes

- src/module/actor/entity.js
Fixes #385.
I'm pretty proud of this one! Rather than place a bandaid, I did some refactoring that I think makes for an overall cleaner rollAttack() function :)
Why did I only minimally touch rollDamage()? I can't figure out where this function is actually used. I think it's used nowhere? It will be useful for enhancements such as #332 so I left it in place for now.
> fix: no longer add zeroes to rolls

- src/module/actor/actor-sheet.js
Fixes #401. 
Also fixes a previously unreported issue (one I noticed), where the Add Spell button on every Level created Level 1 no matter what Level was in that category.
The fix was simple because we are already passing the lvl number with the event dataset. It was just never handled on the actor sheet logic.
> fix: now handling lvl in _createItem correctly

- src/lang/en.json
- src/module/actor/entity.js
- src/templates/actors/dialogs/tweaks-dialog.html
The issue in #410 describes the following as a bug
1. The weapon bonus no longer applies to the attack roll
2. The weapon bonus now applies to the damage roll (implemented before 1.8.3, described as unwanted behavior because the damage box can fulfill this demand)
This pull request fixes problem 1. Problem 2 was the result of an intentional change, and I've already released classicfantasycompendium 1.0.0 in accordance with "Bonus" acting like the RAW weapon bonus
In order to help players use different kinds of bonuses, damage only, AC bonus only, etc, I've added a checkbox to the Tweaks menu that allows an actor to ignore the damage half of the weapon bonus on their owned items
> fix: item weapon bonus added to attack roll

- src/scss/apps.scss
Quick fix in V11testing1's new sidebar layout that keeps the sidebar license info from being in the same row as the system name and version. Going to wait to push until after testing2
> fix(v11): sidebar license info starts on new line

- src/module/actor/actor-sheet.js
When an item folder is dropped from anywhere, items from subfolders are recursively added to the actor sheet (character or monster)
Perhaps people weren't missing this because Compendium Folders module did this for us? I can't remember
> feat: drag item folders into actor sheet

- src/module/actor/actor-sheet.js
I overlooked the fact that compendium folders need to be loaded into memory from their uuids before being dropped into the actor sheet
> fix: compendium folders drag-and-drop

- src/module/actor/entity.js
- src/templates/actors/partials/monster-attributes-tab.html
We had been facing an error where movement details were not getting written to their textbox for a while, and it appeared as though old data may have been wiped. Actually, they were still available in the src of Monster documents, but because their location conflicted with the CharacterMove data model, they were marked as invalid in Foundry and hidden from use.
This changeset moves the movement details storage location to `system.details.movement`, which is more apt for non-gamelogic string data, and creates a data migration where all actors are checked for the old data and moves it to the new location *only* if the new location is empty
> fix: move details now save to monsters correctly

- src/module/dialog/character-creation.js
- src/module/helpers-dice.js
fix for issue #424 
* sets FormApplication option, submitOnClose to false.
* migrated Gather scores to _onSubmit override
* Added default to data.roll.type check in helpers-dice.js, setting isSuccess AND isFailure to false.
* set data object in call to OseDice.Roll to not provide type Object.
I'd quite like to re-work some of this more. But this resolves the reported issue.
Would like to tidy a bit and add two features:
1) Count re-rolls for manually rolled stats (and present totals in final form)
2) Provide a system option for different rolling standards, such as point buy and roll 4d6, deduct the lowest.
> fix(OseCharacterCreator): #424 - don't print on close, don't print Failure() on rolls

- src/module/actor/data-model-classes/__tests__/data-model-character-encumbrance.test.ts
- src/module/actor/entity.js
This fixes a v11-exclusive issue wherein `OseActor.system.prepareDerivedData()` was getting called twice. This was caused by a change in v11 that calls `Actor.system.prepareDerivedData` if it exists on the actor's data model. 
Fixes #446 
Fixes #447
> fix: Character move speed should calculate normally

- src/module/actor/data-model-character.js
- src/module/actor/data-model-monster.js
Fixes #453. We've discovered that the wrong Datafield subtype (ObjectField) was being used to define parts of the datamodel (correct subtype: SchemaField). This was apparently not crucial to the overall DataModel definition in terms of how Foundry handled our system's data model until DataModel validation changed in V11. Foundry no longer uses template.json as a general schema for finding the fields being used if there's a datamodel definition, so I believe it could no longer find the fields because we were using ObjectField incorrectly
Anyway here's a screenshot from Foundry while testing this changeset
> fix: hp/encumbrance attribute bars restored

- src/module/actor/entity.js
Fixes #460 
This function was changed to static as part of a linting pass. We should be checking that we are not changing overrides to static, however, because in this case it caused this `update()` override to never run. The change to static has been reversed. In order to avoid the linter error "do not mutate function properties" we create a clone of the data object property.
This function also returned undefined for all of its conditionals, because (new)`data.system` doesn't exist. The data object's children are flattened into string-keys like this:
I switched to this new way of accessing them.
Finally, the linter is complaining about re-using duplicate string literals. This makes no sense in this context, and indeed it should not be triggering because string literals used as object …
> fix: needs to be non-static in order to override

- src/ose.js
I still can't reproduce #487 locally, but I think the issue could be caused by a redirect that Chrome has some kind of undocumented defenses against (insecure address surely isn't the issue). We're just going to try this address it redirects to
Please excuse me merging this without review: we're just changing a link to another valid link
> Use webaddress it forwards to

- src/module/combat.js
There's a bit of an edge case in the individual initiative code: if a combatant rolls _exactly_ 0 for their initiative (i.e. due to a penalty) after a combat is created but _before_ combat begins, their initiative will be rerolled at the start of combat because the tracker incorrectly assumes it hasn't been. Checking if the value is nullish, instead of falsy, lets the system distinguish between unrolled init and the number 0.
> Fix: Don't reroll zero init at start of combat

- src/module/item/entity.js
Resolves #524.
The method that shows the chat card for an item/ability was referencing `CONST.CHAT_MESSAGE_STYLES` instead of `CONST.CHAT_MESSAGE_TYPES`, which exists. As noted in the issue comments, fixing the reference fixes the behavior. Tested in v11.
> Fix: Item chat cards don't show

- src/module/actor/data-model-classes/data-model-character-scores.ts
Creating a new "character" Actor throws a data preparation error because one or more properties aren't being set before they're accessed. It seems like it's because undefined data is being passed into the `OseDataModelCharacterScores` constructor, since this little hack is enough to fix the error. Harmless as far as I can tell, but those red console messages bug me XD
> Fix: Error on new actor creation

- .github/workflows/release.yml
This adds new step int he workflow to make sure that all `ose-dev` occurances are replaces `ose` in the dist files
> Add new step in the workflow to replace ose-dev with ose

- src/module/helpers-treasure.js
I noticed that the Treasure Tables were always returning No Results.  I looked into it and apparently the docs are wrong for TextEditor.enrichHTML() because it is returning a promise of a string, not a string.  This just awaits that call, which fixes the Treasure Table rolling.  Yay!
> Fix for Treasure Tables not computing successful results.

- src/module/actor/data-model-character.js
Having a Slow weapon equipped currently only slows you down in group initiative if it's the _only_ weapon you have outside of a container. Turns out the isSlow property on the Actor is only true if _all_ of their weapons are both Slow and equipped. Individual initiative likely has the same issue and this change probably fixes that too.
> Fix: Slow weapons forgetting their slowness
